title: Data Science Professional Practice Portfolio
logo: # Add path to your logo if desired (optional)
description: Demonstrating skills across Data Engineering, Visualisation, and Analytics
show_downloads: true
theme: jekyll-theme-minimal
